# UberItems for Craftbukkit / Spigot
# Author: Brandon (ThirtyVirus) Calabrese
#
# YouTube:      https://www.youtube.com/thirtyvirus
# Twitter:      https://twitter.com/ThirtyVirus
# SpigotMC:     https://www.spigotmc.org/members/thirtyvirus.179587/

# FILE: config.yml
# These are the settings for UberItems. Change whatever you like but do not remove any
# non-comment lines, as this will result in errors.

plugin-prefix: "&c&l[&5&lUberItems&c&l] &8&l"

# Custom Setting
custom-setting: false
