main: thirtyvirus.uber.UberItems
version: 1.1
name: UberItems
api-version: 1.13

commands:
  uber:
    description: Main command for UberItems. Use /uber help for more info
permissions:
  uber.user:
    description: Allows player to use the plugin's user features
    default: true
  uber.admin:
    description: Allows player to use the plugin's admin features
    default: op