main: thirtyvirus.uber.UberItems
version: 2.0
name: UberItems
api-version: 1.13

commands:
  uber:
    description: Main command for UberItems. Use /uber help for more info
permissions:
  uber.user:
    description: Allows player to use the plugin's user features
    default: true
  uber.admin:
    description: Allows player to use the plugin's admin features
    default: op
  uber.item.*:
    description: Allows player to use a specific UberItem
    default: true
  uber.rarity.*:
    description: Allows player to use items of a certain rarity
    children:
      uber.rarity.common: true
      uber.rarity.uncommon: true
      uber.rarity.rare: true
      uber.rarity.epic: true
      uber.rarity.legendary: true
      uber.rarity.mythic: true
      uber.rarity.unfinished: true
    default: true